hqz/urls.py
from django.conf.urls import patterns, url
from django.contrib import admin
from hqz import views

admin.autodiscover()
urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'hqz/index.html'},
                           name='login'),
                       url(r'^register/$', views.register, name='register'),
                       url(r'^(?P<pk>\d+)/loginreg/$', views.LoginView.as_view(), name='loginreg'),
                       url(r'^main/$', views.main, name='main'),
                       url(r'^sample/$', views.sample, name='sample'),
                       url(r'^sample2/$', views.sample2, name='sample2'),
)

siteroot/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^hqz/', include('hqz.urls', namespace="hqz")),
                       # url(r'^chat/', include('chat.urls', namespace="chat")),
                       url('^$', include('hqz.urls', namespace="hqz")),
)

hqz/models.py
#!/usr/bin/python
# -*- coding: UTF-8 -*-
import datetime
from django.db import models


# Create your models here.
from hqzauth.models import AppUser


class Degree(models.Model):
    """
    学历。
    如：本科生，硕士生....
    """
    name = models.CharField(max_length=100)
    short_name = models.CharField(max_length=30)

    def __unicode__(self):
        return self.name


class School(models.Model):
    """
    学校
    """
    name = models.CharField(max_length=100)
    short_name = models.CharField(max_length=30)

    def __unicode__(self):
        return self.name

class Activity(models.Model):
    '''
    活动
    '''
    name = models.CharField(max_length=100)
    describtion = models.CharField(max_length=400)
    start_time  = models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0))
    address     = models.CharField(max_length=300)
    ptx   = models.CharField(max_length=200)
    pty   = models.CharField(max_length=200)
    chatrom_num = models.IntegerField(max_length=6, default=0)
    num_people_in_room = models.IntegerField()
class Chatrom(models.Model):
    owner = models.ForeignKey(Activity)
    id  = models.IntegerField(primary_key=True)

class Department(models.Model):
    """
    院系
    """
    name = models.CharField(max_length=100)
    short_name = models.CharField(max_length=30)

    def __unicode__(self):
        return self.name


class Grade(models.Model):
    """
    年级
    """
    name = models.CharField(max_length=100)
    short_name = models.CharField(max_length=30)

    def __unicode__(self):
        return self.name


class Code(models.Model):
    """
    注册码
    """
    register_code = models.CharField(primary_key=True, max_length=50)
    creator = models.ForeignKey(AppUser)
    start_time = models.DateTimeField(auto_now_add=True)
    end_time = models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0))
    type = models.CharField(max_length=20)
    times = models.IntegerField(max_length=6, default=0)

    def __unicode__(self):
        return self.register_code


class SchoolCoterie(models.Model):
    """
    学校圈子，以学校相关信息为单位的圈子
    """
    code = models.OneToOneField(Code, primary_key=True)
    school = models.ForeignKey(School)
    department = models.ForeignKey(Department)
    grade = models.ForeignKey(Grade)
    degree = models.ForeignKey(Degree)

    class Meta:
        db_table = 'hqz_school_coterie'

    def __unicode__(self):
        return self.school.name


class AppUserDetail(models.Model):
    """
    应用程序用户详细信息
    """
    app_user = models.OneToOneField(AppUser, primary_key=True)
    avatar = models.URLField(max_length=255, blank=True)
    school_coterie = models.ForeignKey(SchoolCoterie, blank=True)

    class Meta:
        db_table = 'hqz_app_user_detail'

    def __unicode__(self):
        return self.app_user.get_full_name()

hqz/views.py
#!/usr/bin/python
# -*- coding: UTF-8 -*-

from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.db import transaction, IntegrityError
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views import generic
from conversejs.models import XMPPAccount
from get_friends import RosterBrowser

# Create your views here.
from hqz import logger
from hqz.constants import MAIL_OCCUPIED, REGISTER_CODE_TIMES_INVALID, REGISTER_CODE_NOT_EXIST, INTEGRITY_ERROR
from hqz.models import AppUserDetail, SchoolCoterie,Activity
from hqzauth import AppUser


class IndexView(generic.ListView):
    template_name = 'hqz/index.html'
    context_object_name = 'main_list'

    def get_queryset(self):
        return []

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(IndexView, self).dispatch(*args, **kwargs)


def index(request):
    """
    Index
    """
    return render(request, 'hqz/index.html')


class LoginView(generic.DetailView):
    """
    Login view after registration
    """
    model = AppUser
    template_name = 'hqz/login.html'


def register(request):
    """
    Register new user.
    """
    nickname = request.POST['nickname']
    email = request.POST['email']
    register_code = request.POST['register_code']
    password = request.POST['reg_password']
    sex = request.POST['sex']
    if len(AppUser.objects.filter(email__exact=email)) > 0:
        logger.warn('The mail: {0} has been registered'.format(email))
        return render(request, 'hqz/index.html', {
            'error_message': MAIL_OCCUPIED.format(email),
        })
    if 'male' == sex:
        transformed_sex = True
    elif 'female' == sex:
        transformed_sex = False
    try:
        school_coterie = SchoolCoterie.objects.get(pk=register_code)
        count = len(AppUserDetail.objects.filter(school_coterie__exact=school_coterie))
        if count > 0:
            logger.info('The code %s has been registered for %d times.' % (register_code, count))
            if school_coterie.code.times > 0:
                school_coterie.code.times -= 1
                app_user = AppUser.objects.create_user(email, nickname, transformed_sex, register_code, password)
            else:
                logger.warn('The register code: {0} use times passed'.format(register_code))
                return render(request, 'hqz/index.html', {
                    'error_message': REGISTER_CODE_TIMES_INVALID.format(register_code), })
        else:
            if school_coterie.code.times > 0:
                school_coterie.code.times -= 1
            app_user = AppUser.objects.create_user(email, nickname, transformed_sex, register_code, password)
    except SchoolCoterie.DoesNotExist:
        logger.warn('The register code: {0} does not exist!'.format(register_code))
        return render(request, 'hqz/index.html', {
            'error_message': REGISTER_CODE_NOT_EXIST.format(register_code),
        })
    else:
        try:
            with transaction.atomic():
                school_coterie.code.save()
                app_user.save()
                app_user_detail = AppUserDetail()
                app_user_detail.school_coterie = school_coterie
                app_user_detail.app_user = app_user
                app_user_detail.save()
        except IntegrityError:
            return render(request, 'hqz/index.html', {
                'app_user': app_user,
                'error_message': INTEGRITY_ERROR,
            })
        return HttpResponseRedirect(reverse('hqz:loginreg', args=(app_user.id,)))


def login(request):
    """
    Login
    """
    return render(request, 'hqz/login.html')


@login_required
def main(request):
    """
    Main page
    """
    active_list = Activity.objects.order_by('-start_time')[:5]
    user = request.user;
    xmpp_account = XMPPAccount.objects.get(user=user.pk)
    parsed_username = user.get_username().replace('@', '.')
    logger.warn('parsed name : {0} !'.format(parsed_username))
    xmpp_jid = parsed_username + u'@' + '127.0.0.1'
    xmpp = RosterBrowser(xmpp_jid, xmpp_account.password)
    if xmpp.connect():
        xmpp.process(block=True)
    xmpp.process(block=True)
    logger.warn('friends name : {0} !'.format(xmpp.friends))
    return render(request, 'hqz/main.html',  {
                    'active_list': active_list,'friend_list':xmpp.friends, })


@login_required
def sample(request):
    """
    Only a sample
    """
    return render(request, 'hqz/sample.html')


@login_required
def sample2(request):
    """
    Only a sample
    """
    return render(request, 'hqz/sample2.html')

hqz/templates/hqz/index.html
{% load admin_static %}{% load staticfiles %}{% load firstof from future %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="嗨圈子,hi,圈子,找人,微梦,社交,同学,朋友,活动,交友">
    <meta name="description" content="嗨圈子,让世界嗨起来,让我们一起来参加活动">
    <meta name="author" content="微梦团队">

    <link rel="shortcut icon" href="{% static 'hqz/images/favicon.ico' %}">

    <title>嗨圈子</title>

    <link rel="stylesheet" type="text/css" href="{% static 'hqz/css/bootstrap.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'hqz/css/carousel.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'hqz/css/signin.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'hqz/css/font-awesome.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'hqz/css/custom.css' %}"/>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="{% static 'hqz/js/html5shiv.js' %}"></script>
        <script src="{% static 'hqz/js/respond.min.js' %}"></script>
    <![endif]-->
</head>
{% load i18n %}

<body>

<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">嗨圈子</a>
        </div>
        <div class="navbar-collapse collapse">
            <form novalidate="novalidate" id="login-form" class="navbar-form navbar-right" role="form" method="post"
                  action="{% url 'hqz:login' %}">
                {% csrf_token %}
                <div class="row">
                    <div class="form-group col-md-5">
                        <input type="text" name="username" id="username" placeholder="邮箱"
                               class="form-control required email"
                               data-popover-offset="45,-120">
                    </div>
                    <div class="form-group col-md-5">
                        <input type="password" name="password" id="password" placeholder="密码"
                               class="form-control required"
                               data-popover-position="bottom" data-popover-offset="45,-120">
                    </div>
                    <div class="col-md-2">
                        <button type="submit" class="btn btn-success submit-btn">登录</button>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-5">
                        <label class="checkbox">
                            <input type="checkbox" value="remember-me">记住我
                        </label>
                    </div>
                    <div class="col-md-5">
                        <a href="{% url 'admin:password_change' %}">忘记密码？</a>
                    </div>
                    <div class="col-md-2"></div>
                </div>
                <input type="hidden" name="next" value="{% url 'hqz:main' %}"/>
            </form>
        </div>
        <!--/.navbar-collapse -->
    </div>
</div>

<div class="container">
    <div class="row featurette signup-heading">
        {% if form.errors %}
            <div class="alert alert-danger">你所输入的用户名和密码不匹配，请重新尝试。</div>
        {% endif %}
        {% if error_message %}
            <div class="alert alert-danger">{{ error_message }}</div>
        {% endif %}
    </div>

    <div class="row featurette">
        <div class="col-md-7">
            <img class="featurette-heading img-responsive" src="{% static 'hqz/images/guide.jpg' %}"
                 alt="HI嗨圈子">
        </div>
        <div class="col-md-5">
            <div class="navbar-collapse collapse signup-heading">
                <form novalidate="novalidate" id="signup-form" action="{% url 'hqz:register' %}" class="form-signin"
                      role="form" method="post">
                    {% csrf_token %}
                    <h2 class="form-signin-heading">新用户注册</h2>
                    <input type="text" name="nickname" placeholder="昵称" class="form-control required">
                    <input type="text" name="email" placeholder="邮箱" class="form-control required email">
                    <input type="text" name="register_code" placeholder="注册码"
                           class="form-control required">
                    <input type="password" name="reg_password" placeholder="新密码"
                           class="form-control required">

                    <div class="row">
                        <div class="col-md-4"><label class="radio">
                            <input type="radio" name="sex" value="female" data-popover-position="right"
                                   data-popover-offset="-10, 150">女生
                        </label></div>
                        <div class="col-md-4"><label class="radio">
                            <input type="radio" name="sex" value="male">男生
                        </label></div>
                        <div class="col-md-4"></div>
                    </div>
                    <button class="btn btn-lg btn-primary btn-block" type="submit">注册</button>
                </form>
            </div>
        </div>
    </div>

    <hr>

    <footer>
        <p>&copy; 微梦团队 2014</p>
    </footer>
</div>
<!-- /container -->


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'hqz/js/jquery-1.10.2.min.js' %}"></script>
<script src="{% static 'hqz/js/bootstrap.min.js' %}"></script>
<script src="{% static 'hqz/js/gist-embed.js' %}"></script>
<script src="{% static 'hqz/js/jquery.validate.min.js' %}"></script>
<script src="{% static 'hqz/js/jquery.validate.bootstrap.popover.min.js' %}"></script>
<script src="{% static 'hqz/js/localization/messages_zh.js' %}"></script>
<script src="{% static 'hqz/js/additional-methods.js' %}"></script>
<script type="text/javascript">
    $(function () {
        $('#signup-form').validate_popover({
            popoverPosition: 'right',
            rules: {
                nickname: {
                    required: true,
                    minlength: 3,
                    maxlength: 15,
                    alphanumeric: true
                },
                email: {
                    required: true,
                    email: true
                },
                register_code: {
                    required: true,
                    minlength: 3,
                    maxlength: 80
                },
                reg_password: {
                    required: true,
                    minlength: 6,
                    maxlength: 15
                },
                sex: "required"
            },
            messages: {
                nickname: {
                    required: "昵称不能为空",
                    alphanumeric: "请仅输入字母，数字以及下划线"
                },
                email: {
                    required: "邮箱不能为空"
                },
                register_code: {
                    required: "注册码不能为空"
                },
                reg_password: {
                    required: "密码不能为空",
                    minlength: "密码必须至少为6个字符长"
                },
                sex: "请选择性别"
            }
        });

        $('#login-form').validate_popover({
            popoverPosition: 'bottom',
            rules: {
                username: {
                    required: true,
                    email: true
                },
                password: {
                    required: true,
                    minlength: 6
                }
            },
            messages: {
                username: {
                    required: "邮箱不能为空"
                },
                password: {
                    required: "密码不能为空",
                    minlength: "密码必须至少为6个字符长"
                }
            }
        });
    });
</script>

</body>
</html>

hqz/templates/hqz/login.html
{% load admin_static %}{% load staticfiles %}{% load firstof from future %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="shortcut icon" href="{% static 'hqz/images/favicon.ico' %}">

    <title>嗨圈子</title>

    <link rel="stylesheet" type="text/css" href="{% static 'hqz/css/bootstrap.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'hqz/css/carousel.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'hqz/css/signin.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'hqz/css/font-awesome.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'hqz/css/custom.css' %}"/>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="{% static 'hqz/js/html5shiv.js' %}"></script>
        <script src="{% static 'hqz/js/respond.min.js' %}"></script>
    <![endif]-->
</head>
{% load i18n %}

<body>
<div class="container">
    <div class="alert alert-success">用户：{{ object.nickname }} 注册成功</div>

    <form novalidate="novalidate" id="login-form" class="form-signin" role="form" method="post"
          action="{% url 'hqz:login' %}">
        {% csrf_token %}
        <h2 class="form-signin-heading">请登录</h2>
        <input type="text" name="username" class="form-control required email" placeholder="邮箱"
               value="{{ object.email }}" autofocus>
        <input type="password" name="password" class="form-control required" placeholder="密码"
               data-popover-position="right">
        <label class="checkbox">
            <input type="checkbox" value="remember-me">记住我
        </label>
        <button class="btn btn-lg btn-primary btn-block" type="submit">登录</button>
        <input type="hidden" name="next" value="{% url 'hqz:main' %}"/>
    </form>

    <hr>

    <footer>
        <p>&copy; 微梦团队 2013</p>
    </footer>
</div>
<!-- /container -->


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'hqz/js/jquery-1.10.2.min.js' %}"></script>
<script src="{% static 'hqz/js/bootstrap.min.js' %}"></script>
<script src="{% static 'hqz/js/gist-embed.js' %}"></script>
<script src="{% static 'hqz/js/jquery.validate.min.js' %}"></script>
<script src="{% static 'hqz/js/jquery.validate.bootstrap.popover.min.js' %}"></script>
<script src="{% static 'hqz/js/localization/messages_zh.js' %}"></script>
<script src="{% static 'hqz/js/additional-methods.js' %}"></script>
<script type="text/javascript">
    $(function () {
        $('#login-form').validate_popover({
            popoverPosition: 'right',
            rules: {
                password: {
                    required: true,
                    minlength: 6
                }
            },
            messages: {
                password: {
                    minlength: "密码必须至少为6个字符长"
                }
            }
        });
    });
</script>
</body>
</html>

hqz/templates/hqz/main.html
{% load staticfiles %}{% load conversejs %}
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'/>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge"/>
    <meta name="description" content="嗨圈子"/>
    <link rel="shortcut icon" href="{% static 'hqz/images/favicon.ico' %}">
    <title>嗨圈子</title>
    {% comment %} {% conversejs_static %} {% endcomment %}
    <link rel="stylesheet" type="text/css" href="{% static 'hqz/css/bootstrap.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'hqz/css/bootstrap-theme.min.css' %}"/>
    {% comment %}<link rel="stylesheet" type="text/css" href="{% static 'hqz/css/theme.css' %}"/> {% endcomment %}

    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'hqz/css/carousel.css' %}"/>
    <script src="{% static 'hqz/js/bootstrap-carousel.js'%}"></script>
    {% comment %}<script src="{% static 'hqz/js/strophe.js' %}"></script>{% endcomment %}
    {% comment %}<script src="{% static 'hqz/js/converse.min.js' %}"></script>{% endcomment %}
    <script src="{% static 'hqz/js/locale/locales.js' %}"></script>
    <script src="{% static 'hqz/js/jquery-1.10.2.min.js' %}"></script>
    <style>
      body {
        background-color: #EFEFEF;
      }
   
    </style>
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="{% static 'hqz/js/html5shiv.js' %}"></script>
        <script src="{% static 'hqz/js/respond.min.js' %}"></script>
    <![endif]-->
</head>
<body>
	<div class="navbar navbar-static">
		<div class="container">
			<div class="nav pull-left navbar-nav">
				<a target="ext" href="#">
					<img src="{% static 'hqz/images/logo.png' %}" alt="">
				</a>
			</div>
			
			<div class="nav pull-right navbar-nav">
				<a href="">
				<img src="{% static 'hqz/images/logout.png' %}" alt="">
				</a>
			</div>
		</div>
	</div>
	
	<div class="container">
		<div class="row">
			<div class="col-md-1">
				<button type="button" class="btn btn-default btn-lg btn-hiquanzi-left-large btn-hiquanzi-style1">
					<span class="glyphicon glyphicon-chevron-left hiquanzi-white"></span> 
				</button>
			</div>
			<div class="col-md-10">
				<div id="myCarousel" class="carousel slide">
					<div class="carousel-inner">
                        {% if active_list %}
                            {% for active in active_list %}
                               {% if forloop.counter == 1  %}

                            	<div class="item active">
							<div id="slide-1" class="row">
								<div class="carousel-caption-1">
									<h1>{{  active.name  }}</h1>
									<h4>{{ active.start_time|date:"Y年m月d日" }}   {{ active.address }}</h4>
								</div>
								<div class="carousel-caption-2">
									<p><a class="btn btn-lg btn-primary" role="button" href="#">开始活动</a></p>
								</div>
							</div>
						</div>
                                   {% else %}
                                   	<div class="item">
							<div id="slide-1" class="row">
								<div class="carousel-caption-1">
									<h1>  {{  active.name  }}</h1>
									<h4>{{ active.start_time|date:"Y年m月d日" }}   {{ active.address }}</h4>
								</div>
								<div class="carousel-caption-2">
									<p><a class="btn btn-lg btn-primary" role="button" href="#">开始活动</a></p>
								</div>
							</div>
						</div>
                                {% endif %}

                            {% endfor %}
                            {% else %}
                            <div id="slide-1" class="row">
								<div class="carousel-caption-1">
									<h1>没有活动</h1>
									<h4>{{ active.start_time|date:"Y年m月d日" }}   {{ active.address }}</h4>
								</div>

							</div>
                        {% endif %}
						

						

					</div>

					<div class="row carousel-caption-3">
						<a data-slide="prev" href="#myCarousel">
							<div class="col-md-4">
								<img src="{% static 'hqz/images/s02.png' %}" alt="">
								<h4>上个活动</h4>
							</div>					
						</a>
						<div class="col-md-4">
						</div>
						<a data-slide="next" href="#myCarousel">
							<div class="col-md-4">
								<img src="{% static 'hqz/images/s03.png' %}" alt="">
								<h4>下个活动</h4>
							</div>						
						</a>
					</div>						

				</div>	
				<div class="row">
					<div class="col-md-1">
						<h3>基</h3>
						<h3>友</h3>
						<h3>帮</h3>
					</div>
					<div class="col-md-1">
						<button type="button" class="btn btn-default btn-lg btn-hiquanzi-left-small btn-hiquanzi-style1">
							<span class="glyphicon glyphicon-chevron-left hiquanzi-white"></span> 
						</button>
					</div>
					<div class="col-md-9">
						<div class="row">
                            {% if friend_list %}
                                {% for friend in friend_list %}
							<div class="col-md-3">
								<a href="#" class="thumbnail">
								
									<img src="{% static 'hqz/images/face.png' %}" alt="">
                                    <p>{{ friend }}</p>
								</a>
							</div>
                                {% endfor %}
                            {% endif %}
							<div class="col-md-3">
								<a href="#" class="thumbnail hiquanzi-span-center">
									<span class="glyphicon glyphicon-plus btn-hiquanzi-add"></span>
								</a>
							</div>	
						</div>						
					</div>
					<div class="col-md-1">
						<button type="button" class="btn btn-default btn-lg btn-hiquanzi-left-small btn-hiquanzi-style1">
							<span class="glyphicon glyphicon-chevron-right hiquanzi-white"></span> 
						</button>	
					</div>						
				</div>

			</div>
			<div class="col-md-1">
				<button type="button" class="btn btn-default btn-lg btn-hiquanzi-left-large btn-hiquanzi-style1">
					<span class="glyphicon glyphicon-chevron-right hiquanzi-white"></span> 
				</button>			
			</div>			
		</div>	
	</div>




{% conversejs_initialize %}


<!-- Bootstrap core JavaScript
    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'hqz/js/bootstrap.min.js' %}"></script>


{% comment %}<script src="{% static 'hqz/js/bootstrap.min.js' %}"></script>
<script src="{% static 'hqz/js/holder.js' %}"></script>{% endcomment %}
</body>
</html>

hqz/templates/hqz/sample.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'/>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge"/>
    <meta name="description" content="Converse.js: Open Source Browser-Based Instant Messaging"/>
    <link rel="stylesheet" type="text/css" href="{% static 'hqz/css/stylesheet.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'hqz/css/converse.css' %}"/>
    <!--<script data-main="main" src="components/requirejs/require.js"></script>-->
    <script src="{% static 'hqz/js/converse.min.js' %}"></script>
    <script src="{% static 'hqz/js/locale/locales.js' %}"></script>
    <script src="{% static 'hqz/js/locale/single_locale.js' %}"></script>
    <title>Converse.js</title>
</head>

<body>
<!-- HEADER -->
<div id="header_wrap" class="outer">
    <header class="inner">
    </header>
</div>

<!-- MAIN CONTENT -->
<div id="main_content_wrap" class="outer">
</div>

<!-- FOOTER  -->
<div id="footer_wrap" class="outer">
    <footer class="inner">
        <p class="copyright">Converse.js created by <a href="/" target="_blank">jcbrand</a></p>
    </footer>
</div>

<div id="conversejs"></div>

<script type="text/javascript">
    var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
    document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">try {
    var pageTracker = _gat._getTracker("UA-2128260-8");
    pageTracker._trackPageview();
} catch (err) {
}</script>
</body>
<script>
    require(['converse'], function (converse) {
        converse.initialize({
            allow_otr: true,
            auto_list_rooms: false,
            auto_subscribe: false,
            // bosh_service_url: 'https://conversejs.org/http-bind', // Please use this connection manager only for testing purposes
            bosh_service_url: 'http://localhost/http-bind',
            debug: true,
            hide_muc_server: false,
            i18n: locales['de'], // Refer to ./locale/locales.js to see which locales are supported
            prebind: false,
            show_controlbox_by_default: true,
            xhr_user_search: false
        });
    });
</script>
</html>